# Generated by Django 6.0.3 on 2026-04-07 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('processed_resume', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('uploaded_post', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('returned_resume', models.FileField(blank=True, null=True, upload_to='generated_resumes/')),
                ('returned_processed_resume', models.TextField(blank=True, null=True)),
                ('resume_feedback', models.TextField(blank=True, null=True)),
                ('old_skills', models.JSONField(blank=True, default=list)),
                ('new_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('old_experience_matches', models.JSONField(blank=True, default=list)),
                ('new_experience_matches', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_task_status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('feedback_task_status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
